# -*- coding: utf-8 -*-
"""Object Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Tyw6OfFWqboXpvBfsU-XPxXBAxu5pGY
"""

import tensorflow as tf

tf.__version__

!pip install keras==2.4.3 numpy==1.19.3 pillow==7.0.0 scipy==1.4.1 h5py==2.10.0 matplotlib==3.3.2 opencv-python keras-resnet==0.2.0

!pip install imageai --upgrade

!wget -O resnet50_coco_best_v2.1.0.h5 https://github.com/OlafenwaMoses/ImageAI/releases/download/essentials-v5/resnet50_coco_best_v2.1.0.h5

from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.1.0.h5"))
detector.loadModel()

!wget -O input_video.mp4 https://www.dropbox.com/sh/p2m8a02tb1obpwg/AABQxXJucyTBIuVK0VeuI0a7a/DS-IQ-002-ObjectDetect-Video.mp4?dl=0

video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "input_video.mp4"),
                            output_file_path=os.path.join(execution_path, "traffic_detected")
                            , frames_per_second=20, log_progress=True)
print(video_path)

